<?php

namespace Tests\Unit;

use App\User;
use Mockery as M;
use App\Http\Requests\PostRequest;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class PostRequestTest extends TestCase
{
    /**
     * @var PostRequest
     */
    private $request;

    /**
     *
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->request = $this->getMockBuilder(User::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->request->expects($this->any())
            ->method('hasRole')
            ->willReturn(false);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testExample()
    {
        $rules = $this->request->rules();
        $this->assertNotEmpty($rules);
        $this->assertArrayHasKey('title', $rules);
        $this->assertNotEmpty($rules['title']);
        $rules = explode('|', $rules['title']);
        $this->assertNotEmpty($rules);
        $this->assertContains('asdasdsa', $rules);
    }
}
